language: node_js
node_js:
- '7'
- '8'
- '9'
- '10'
notifications:
  slack:
    secure: lQ7L0opamvKCS8Ae/S2a60keyLn2rHKCJ/eOUhOmJec7cBPjuycp7kC19CvrrUVVYh70gU/auiCtLti26+qDpgDC5P9q+VUS73a4K0dqvok/C38z4g27en8jW1FYTWj82NKFhS4oO3JhqyZZ/V0+Bn6MJfPBxvj+jHP81ib9LI6i3D0rTpuQGvE0A4ENu3Wfik6gLnLRx79IDujWskF3kM1S/BLq8XjzqHUykYqXC/3G4phesyiTJxNWvcztYnwhPN0dVf6K2f1YdBDPBJU8IlXMx6+SUmMkHhapLiohpbmnSZsouMqh2V97DvxRJzu27pv+bBRK5e11HP9OOAmFFxbLxka+05f+U5n4BvSfXn/RqEa5q7ZgDj3fI3E6knMPu8+S+kEHk0/q4I9rof6lijOa7KGnFY8sNud0dBnfSdhDxyLg/7T5H/PsEuOJBY44n0Db7KeVVLZ5rQuLH3kCGDNByPV84Pl0XRy4a3IqEFIjECvxGrxJDTTddu/llC1xQSQdBsMqr4QWICVJKgn0gIB+2YcyWtb4Da/eoDt6QDrX0rn56QR2OBzlQgk12F7vxYZqrWZ+IIPdeT6pNq1ij/sfI2S1som26DrwYtF4ALxEdGfHemL0VNFyfZWLqAIbzmYjoDMn/onAsNa6A8aIG3fzJzLFmrWuLzS35a+qNfY=
