language: node_js
os: linux
dist: xenial
node_js:
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: 14
      deploy:
        provider: npm
        email: rogier+npm@konfirm.eu
        on:
          branch: master
          tags: true
        api_key:
          secure: SEMgZ7WUVs9RVhuDhGAlp+gYV1YJixGgRi4E/XfzHPGbZg1lqbqXKecYRgpzCbZ93xO2q+DS97TKumB6ScD8Yd/0LXIJ1j8XphR+KQDevMYmz4Rk43XDrMHyN8PB092U/2ifvoqAXZxP74NX3423n/TCHovRaTGENxmZIJm8njYBgQEiPjK0dNlqe+hFMWlByx0vLDEs2/K3eIwA0OYoMdWFDAmaSt4QfDI7YcIT1/SJlGTDIblCEWHW+FvJPtTiqvvJyRECctKPLnKZctuma/qnuqHANp6p+E9B+951O8DyxTyec5Y2sZBZOoYYGhTOdxsRhArsRveB73MTfDzZ1cPrj3fQAaD+K4GbQ/u6gsnMg77NhYwtEKAA6+O8XV1c4Xgq3BHTuKFbvKKyID0r0e5FgX6xc5++CivOQvXk3IjMcf3zjrFlQA4dZ8mQsTI5FYsAshhI9rd2v17t3x2SQjNMOkYIlZ0ym/2Fysq8KbCSthyOimKcX3/zyHiHFZEb0ip4m23Z3HaaIONmESeYVBTdVcl9QqTBxpEDSrlZVJ0w+Et4IkLdJdcmUed1T7WWno/lbq4X0JjkGapOiDzF2BkyB96ufiHs5ENQ71Xvkn87SAgVDV2t03GgP5llvMpoPiKAgCyi+W50z8P7q67p2O7DGCfbEzb0UeuH38lSRPY=
